version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app/frontend
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  app:
    driver: local